service: example

provider:
  name: aws
  runtime: go1.x
  region: "eu-central-1"
  stage: ${opt:stage, 'dev'}
  environment:
    COURSE_TABLE_NAME: courses-${opt:stage, self:provider.stage}
    USER_TABLE_NAME: users-${opt:stage, self:provider.stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create_course:
    handler: bin/course/create
    events:
      - http:
          path: courses
          method: post
  read_course:
    handler: bin/course/read
    events:
      - http:
          path: courses/{id}
          method: get
  update_course:
    handler: bin/course/update
    events:
      - http:
          path: courses/{id}
          method: put
  delete_course:
    handler: bin/course/delete
    events:
      - http:
          path: courses/{id}
          method: delete
  list_courses:
    handler: bin/course/list
    events:
      - http:
          path: courses
          method: get
  create_user:
    handler: bin/user/create
    events:
      - http:
          path: users
          method: post
  read_user:
    handler: bin/user/read
    events:
      - http:
          path: users/{id}
          method: get
  update_user:
    handler: bin/user/update
    events:
      - http:
          path: users/{id}
          method: put
  delete_user:
    handler: bin/user/delete
    events:
      - http:
          path: users/{id}
          method: delete
  list_users:
    handler: bin/user/list
    events:
      - http:
          path: users
          method: get
  
resources:
  Resources:
    CourseDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: B
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'courses-${opt:stage, self:provider.stage}'
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: B
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'users-${opt:stage, self:provider.stage}'
